### ISSUE TITLE
Bug: update one to one frequency distribution buckets

### ISSUE THREAD

**Issue by Jasthin** [microsoft/wpa#114]
**Describe the bug**
The one to one frequency distribution function has a category for frequency of 1:1 meetings that are less than a week, which should not exist. Can we align the categories to the manager dashboard and label them: 
1. Twice monthly or more (up to 3 weeks)
2. Monthly (3 - 6 weeks)
3. Bi Monthly (6-10 weeks)
4. Quarterly or less (10 +)

**Comment by martinctc** [comment]
Thanks for this submission @Jasthin! 

I will translate this as follows, with the end expression representing _n_ times of 1:1 meetings per week (where `n` == 1 means exactly once per week):

- **Quarterly or less (10 +)**: `n` <= 0.1 
- **Bi Monthly (6-10 weeks)**: `n` <= 0.1666 & `n` > 0.1
- **Monthly (3 - 6 weeks)**: `n` <= 0.333 & `n` > 0.1666
- **Twice monthly or more (up to 3 weeks)**: `n` > 0.333

In this case, where `n` equals 0 it would mean that there are no 1:1s happening at all over the entire period of observation.

Does this match what you would expect?

Also, was wondering whether the label **More than twice a month** would be a clearer label than **Twice monthly or more**?

**Comment by Jasthin** [comment]
Thanks @martinctc ! 

That would match! Does this mean we would have 5 final categories with a category for those receiving no 1:1? That would be a super powerful metric to have! 

Also, I think that rewording makes sense!
