### ISSUE TITLE
Feature request: reintroduce and improve 'old' `workpatterns_classify()` visual

### ISSUE THREAD

**Issue by moralec** [microsoft/wpa#143]
**Describe the bug**
Some issues with workpatterns_classify 

1. We used to have an old visualisation that is prefered by some analysts
2. Old visualisation and area plot need new colours.

**Comment by martinctc** [comment]
![image](https://user-images.githubusercontent.com/17925865/122375752-6c3f6680-cf5b-11eb-872c-115aaf40ac4d.png)

The plot being referred to is this one - which will be addressed in the pull request #160.

**Comment by martinctc** [comment]
![image](https://user-images.githubusercontent.com/17925865/122378639-099b9a00-cf5e-11eb-9a65-3e7debdd50de.png)

This is the new view that would be added, which is consistent with the visual created with `workpatterns_rank()`
