### ISSUE TITLE
Bug: dependency error for `network_p2p(display = "leiden")`

### ISSUE THREAD

**Issue by moralec** [microsoft/wpa#145]
**Describe the bug**
Running network_p2p with option "leiden" results in a error:

Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'leidenalg'

**To Reproduce**
Steps to reproduce the behaviour:
1. Install latest version of the package: install.packages("wpa")
2. Simulate p2p network: p2p_data <- p2p_data_sim(size = 50)
3. Run Leiden plot: p2p_data %>% network_p2p(display = "leiden", path = NULL, return = "plot")

**Screenshots**
![image](https://user-images.githubusercontent.com/62895857/118291085-19dbd780-b4cf-11eb-8f09-1709d77fb182.png)

**Additional context**
Testing modules <- reticulate::py_module_available("leidenalg") shows that the module was not installed.
It can be solved by running py_install("python-igraph") and  py_install("leidenalg") and then running our code

An additional step may be required in the code to solve the issue?

**Comment by moralec** [comment]
hey @martinctc - do you think it would be possible to add py_install("python-igraph") and py_install("leidenalg") directly to the code that plots the graph?

**Comment by martinctc** [comment]
> hey @martinctc - do you think it would be possible to add py_install("python-igraph") and py_install("leidenalg") directly to the code that plots the graph?

CRAN has some restrictions on whether we can automatically install packages (Python packages, in this case) without user intent / approval - which I agree with. In the latest pull request #149, I added this instruction to the documentation, but what we can also add is a more elaborate warning message when 'leiden' is not installed.
