### ISSUE TITLE
Feature request: Color coding adaptability for graphics from functions such as meeting_trend()

### ISSUE THREAD

**Issue by juliajuju93** [microsoft/wpa#188]
**Describe the solution you'd like**
The graphical outcomes from functions like meeting_trend() are great. It would be very helpful if we can hand over a parameter to the function to adjust color coding of those graphs. 

**Additional context**
I have gotten the feedback from some customers that those colors sometimes don't work for the customers or they just want to adjust it to their layout.

**Comment by martinctc** [comment]
This issue is resolved in #175.
