### ISSUE TITLE
`workpatterns_report()` function mislabeling activity of collaboration

### ISSUE THREAD

**Issue by KasWanders** [microsoft/wpa#189]
Hi,

When running the workpatterns_report() function and I am getting results that do not fully make sense. In certain cases, I am returned 0 - < 3h patterns that look more like >9h patterns. Additionally, I sometimes see 0 - < 3h patterns in the >8h archetype. This tends to happy when I play around with the signals e.a. only analyze e-mails or analyze emails, IMs and meetings. 
My expectations is that 0 - < 3h patterns are classified in the low activity archetype and that the >9h patterns are either classified as always on or long continuous/flexible work day.

I am using R version 4.1.1.
The arguments I passed are either:

```
workpatterns_report(
  data,
  hrvar = "Organization",
  signals = c("email", "IM","Meetings"),
  start_hour = "0800",
  end_hour = "1700",
  path = "workpatterns report v",
  timestamp = TRUE)
```

As mentioned in other cases:

`signals = c("email", "IM","unscheduled_calls","meetings")`
or 
`signals = "email"`

I noticed that the sample data only contains emails and IMs so its hard to reproduce the error as the structure is also different and the file is more complex.

See images:

![image](https://user-images.githubusercontent.com/30723574/134370074-04e4dd3f-69bc-4e85-8df1-85c84974378f.png)

![image](https://user-images.githubusercontent.com/30723574/134369520-5f227de4-2708-45bb-bcc6-f9f2ea4e1f98.png)

![image](https://user-images.githubusercontent.com/30723574/134369625-19a62455-aa9a-46a3-860c-cdf6a1b0b29d.png)

**Comment by martinctc** [comment]
Hi @KasWanders, thanks for submitting this issue and for describing your inputs. My key suspicion is line 77 in [`workpatterns_report.R`](https://github.com/microsoft/wpa/blob/532c673ff7746c958cc1d505afa860d4cb990968/R/workpatterns_report.R), where the values of the `signal` argument in `workpatterns_report()` is not passed to the plotting function `workpatterns_rank()`. This will explain why that the error is not reproducible with the sample dataset. I will create a pull request to remedy this and let you know once it is ready to test, thank you!

**Comment by moralec** [comment]
Thank you @KasWanders  for helping us improve the code. 
@martinctc  I think that issue in line 77 may explain the issue of pattern 8 in the 5 - Long continuous workday archetype (basically IM and calls are not showing, so the rank function is not plotting some missing buckets).

However that can't explain why we have patterns with more than 3 hours in the  <3 hour bucket (Like pattern 6). This looks more as a classification problem.  I suspect it may come from 'combine_signals.R'? can you double check if it can actually handle more than two signals?

**Comment by martinctc** [comment]
@moralec - yes you are also correct, `combine_signals()` itself has a `signals` argument that isn't being used within `workpatterns_rank()`. I can update this one as well in the pull request, and check for elsewhere where it exists. Will also add in new signals for the `em_data` to ensure that this will be tested in future CI/CD

**Comment by KasWanders** [comment]
Thanks for the effort @martinctc & @moralec. Pardon, don't have time to dive into the code myself. I like the suggestion to extend sample data
