### ISSUE TITLE
Collaboration_report needs Collaboration_hours metric scan update

### ISSUE THREAD

**Issue by Rory-OG** [microsoft/wpa#193]
Currently, various functions in the report require the Collaboration_hrs metric specified as Collaboration_hours. The report function is no longer consistent with the table headers generated by WPA queries.

**Comment by martinctc** [comment]
Thanks for logging this issue @Rory-OG! If you run `standardise_pq()`, this is a function that does variable name changes that make the variable names from the Ways of Working Assessment Query consistent with the Standard Person Query - this basically renames `Collaboration_hrs` to `Collaboration_hours`. 

If you import the CSV query into R using `import_wpa()`, this variable renaming can be set up in the import process by setting the `standardise` argument to `TRUE`. 

We also have a range of 'flexible' functions like `create_bar()` and `create_line()` where the variable name is supplied directly to the argument, which can help address ad-hoc scenarios where there is a variable name mismatch.

**Comment by Rory-OG** [comment]
Ah good to know! Thanks for clarifying that. I must have missed that function when reading through the function list.

-Rory
