### ISSUE TITLE
Layout of network graph

### ISSUE THREAD

**Issue by FlorineSegers** [microsoft/wpa#44]
When I am plotting a network graph (using Louvain) the layout seems to be random. 

Can we consider enabling the option of a force-directed layout that minimizes edges crossing and prevents overlap? (like Fruchterman-Reingold or Kamada Kawai?

**Comment by martinctc** [comment]
This can currently be done with passing "fr" (Fruchterman-Reingold) to the `algorithm` argument in `network_leiden()` or `network_louvain()`. 

However, the current shortcoming is that this only works if you use the "pretty" (default) plotting method, and won't work if the function uses the "fast" (igraph) plotting method. This will be addressed in the upcoming PR (see #41).

**Comment by martinctc** [comment]
#41 now fully addresses the issue - closing this now.
