### ISSUE TITLE
Enhancement: improve output of the "describe" function 

### ISSUE THREAD

**Issue by FlorineSegers** [microsoft/wpa#45]
When passing "describe" to the return function I get a list of combination of attributes with a % that describes what percentage of the total population in the company with that respective (combination of) attribute(s) falls in the respective community. 

I expect the function to return the opposite: the % of of the communities population with that respective (combination of) attribute(s). 

Can we fix this? 

Second it would be nice to shorten the list of outputs by filtering on a combination of a minimum of 2 attributes (most of the time 1 attribute on it's own doesn't help very much).

**Comment by martinctc** [comment]
This is resolved after merging PR #41, thanks
