### ISSUE TITLE
Variable name check should be optional in check_query function

### ISSUE THREAD

**Issue by moralec** [microsoft/wpa#68]
**Is your feature request related to a problem? Please describe.**
We are currently using check_query(return = "text") at the beginning of each one of our reports. This is a great summary of what the query contains, but also checks the names of variables. This seems out of place. 

**Describe the solution you'd like**
Make the name check optional

**Comment by martinctc** [comment]
Thanks @moralec - this feature is already possible within `check_query()` by setting the `validation` argument to `TRUE`. When this is set to `TRUE`, variable name checks are not shown. I will update this as a documentation issue and resolve this in #67.
