### ISSUE TITLE
collaboration_sum() error - not outputting my unscheduled_call_hours and instant_messages

### ISSUE THREAD

**Issue by juliajuju93** [microsoft/wpa#72]
**Describe the bug**
I tried to run the collaboration_sum() function with some data but it was only showing me Email and Call hours. But I know that we also have "teams" data available.
 
I looked at the basis of the function and it seemed to have problems with the if line of "unscheduled Calls".

In my dataset it was name "unscheduled_call_hours.
 
So I had to rename the col with:
colnames(clean_ca)[colnames(clean_ca) == "Unscheduled_call_hours"] <- "Unscheduled_Call_hours"
 
And after that it worked for me -> I now have the hoped for table:
![image](https://user-images.githubusercontent.com/42241691/108249326-3b8a2480-7155-11eb-9888-74882b61ab86.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/42241691/108249219-172e4800-7155-11eb-944e-f0efc5aff048.png)

**Comment by martinctc** [comment]
Great spot and thanks, @juliajuju93. Have fixed this in #81, where the variable name checks are relaxed so you shouldn't encounter this issue anymore.
