### ISSUE TITLE
import_wpa does not support double-bite characters

### ISSUE THREAD

**Issue by Yuichen12** [microsoft/wpa#73]
**Describe the bug**
When a query data with double bite characters is imported using import_wpa, those characters are garbled.

**To Reproduce**
1. Prepare query data with double bite characters as values (not headers, of course)
2. Use import_wpa to import the data
3. View the imported data. You will see gabled characters in the table.

**Expected behavior**
Double bite characters should remain legible.

**Screenshots**
None

**Additional context**
Specifying encoding as UTF-8 should solve this bug.

**Comment by martinctc** [comment]
Hi @Yuichen12 - thanks for the issue! Can you provide an example of what a double bite character might be? We can use that to test whether the fix has been implemented correctly.

**Comment by martinctc** [comment]
@Yuichen12 - This should now be resolved. 

It worked with a test with some made-up data with a minimal Person Query structure: 
![image](https://user-images.githubusercontent.com/17925865/108405493-0b0bbe80-7219-11eb-85f1-915c7e150616.png)
