### ISSUE TITLE
Discussion: `After_hours_collaboration_hours` does not contain all after-hour metrics

### ISSUE THREAD

**Issue by juliajuju93** [microsoft/wpa#74]
**Describe the bug**
Looking at my data I saw that After_hours_collaboration_hours does only contain emails and meeting metrics. I had to also merge calls and IMs with them

**Expected behavior**
data2 <- data %>% mutate(After_hours_collaboration_hours =
                                  select(.,
                                         After_hours_email_hours,
                                         After_hours_meeting_hours,
                                         After_hours_in_calls,
                                         After_hours_instant_messages) %>%
                                  apply(1, sum))

**Comment by martinctc** [comment]
@juliajuju93 Thanks for the issue! The crux of this is that `After_hours_collaboration_hours` is dependent on the product computation, so it may be confusing for the user if the function re-computes this. We can provide more clarity on the documentation, but the rationale behind limiting such calculations is to make sure that the metrics users compute from {wpa} would map on to the definitions they find in the product documentation. Does that make sense or help?

**Comment by moralec** [comment]
Also take into account that calls and meetings overlap! :) 

In any case, this should get fixed soon in the product itself 👍🏽

**Comment by juliajuju93** [comment]
Perfect - thank you guys for the explanation! It does make sense now. Just trying to recreate the WoW and I had to use this function to get the wished outcome

**Comment by MsMelissa** [comment]
I am working with demo data set and experiencing the same issue.  Thanks team!

**Comment by martinctc** [comment]
This will be something that has to be addressed with Workplace Analytics rather than this R package - closing this issue now.
