### ISSUE TITLE
Feature: option in `extract_hr()` to exclude single-group variables (e.g. Domain, Timezone)

### ISSUE THREAD

**Issue by moralec** [microsoft/wpa#78]
**Is your feature request related to a problem? Please describe.**
Currently extract_hr does a good job at extracting the full list of available HR variables available. However, many tenants include columns that constant (e.g. Domain, Timezone), and these are not useful for analysis /  affect some applications (e.g. create_Rank). See example below.

**Describe the solution you'd like**
 It would be good that extract_hr had an option to exclude HR attributes without variability.  Potentially a exclude_constants parameter like:
extract_hr(data, exclude_constants= TRUE, max_unique = 50, return = "names")

**Example**
![image](https://user-images.githubusercontent.com/62895857/108506789-4659cc00-72b1-11eb-87a7-9c0f2811b225.png)

**Comment by martinctc** [comment]
This is a good feature to add. In terms of the argument, would we prefer `exclude_constants` (logical) or something even more flexible, like `min_unique()` (numeric)? The benefits of `min_unique()` is that it is like a parallel to `max_unique()`, and you can exclude not just single-value attributes but also 2-value, 3-value, etc. However, I agree that this view is less intuitive and `exclude_constant` covers the majority of use cases for a floor threshold.

**Comment by rosamaryo** [comment]
I think this feature would be really helpful for the scenario listed in the example e.g. create_rank and to have as a parameter (exclude_constants) that can be applied whenever needed. Agree that that method would be the most straightforward as opposed to giving even more flexibility for 2-value, 3-value fields. But for the validation report, I would keep the defaults as they are, where all variables are listed in the summary
