### ISSUE TITLE
Feature request: Add a custom option for create_bar to show people 

### ISSUE THREAD

**Issue by moralec** [microsoft/wpa#88]
This:

![image](https://user-images.githubusercontent.com/62895857/109341544-79c4c980-7862-11eb-83ef-bbcb6ca60e7f.png)

Source: https://www.listendata.com/2019/06/create-infographics-with-r.html

**Comment by moralec** [comment]
I don't think we should do this anymore 🤣

**Comment by martinctc** [comment]
Will close this issue for now! We can resurface this if there is a new simple way to implement this or if there is a new emerging use case.
