### ISSUE TITLE
Feature change: align data validation logic with Power BI dashboards

### ISSUE THREAD

**Issue by martinctc** [microsoft/wpa#94]
Currently, there are certain known differences in logic which makes the data validation process between the R package different to the Power BI dashboards. For instance:

1. {wpa} uses the direct **Collaboration_hours** metric which currently does not include `Unscheduled_Call_hours` and `Instant_Message_hours`. The Power BI dashboard calculates this. 
1. `identify_nkw()` uses a _greater than_ (`>`) for the collaboration hours threshold. In the Power BI, _greater than or equal to_ (`>=`) logic is used. The current workaround is to supply a value like 4.9999 instead of 5 to align. 

The first point also applies to `After_hours_collaboration_hours` (as mentioned in #74), but does not affect data validation.

**Comment by moralec** [comment]
Oh good one. I think this actually goes beyond data validation, as some of the metrics in assessments will look different right?
