### ISSUE TITLE
Feature request: New plot for `workpatterns_classify()`

### ISSUE THREAD

**Issue by moralec** [microsoft/wpa#97]
![image](https://user-images.githubusercontent.com/62895857/110157068-ad15d400-7ddf-11eb-8a7d-a6e1704e00da.jpeg)

**Comment by MsMelissa** [comment]
+1 on this feature request

**Comment by martinctc** [comment]
Have created an internal function that allows the generation of this plot. We can call this within `workpatterns_report()` to surface this visual:

![image](https://user-images.githubusercontent.com/17925865/113330280-75367980-9316-11eb-909a-a6d0572e6853.png)

This is created in PR #119.
